// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SocketIO","status":true,"description":"v2.0.4 - Socket.IO (for Alpha NET plugin)","parameters":{}},
{"name":"Alpha_NET_build","status":true,"description":"v0.6.774 Network system (Beta)","parameters":{"Alpha NET":"","ActorsForPlayers":"1, 2, 3, 4","NetworkEvents":"--- --- --- --- ---","ServerStarted":"0","OnConnect":"0","OnDisconect":"0","OnOtherCon":"0","OnOtherDisc":"0","_supporters":"Thanks to these guys!","Donald Derrick":"","Ilya Chkoliar":"https://elushisgaming.club/","Elindos Phar":"","Sarcastic Sloth":""}}
];
